<a href="https://colab.research.google.com/github/bbberylll/ESAA_OB/blob/main/ESAA_OB_F04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텍스트 분석

### NLP vs Text Mining
: NLP는 텍스트 분석을 정교하게 발전하게 해주는 기반 기술

: 텍스트 분석은 비정형 데이터를 분석하는 것. 따라서 **비정형 텍스트 데이터를 피처 형태로 추출하고, 피처에 의미 있는 값을 부여하는 과정**이 필수적.
  
  * 피처 벡터화(=피처 추출)

        텍스트를 word 기반을 피처로 추출 >> 단어 빈도수 부여
        = 텍스트는 단어의 조합인 벡터값으로 표현됨

      * 예시 : BOW, Word2Vec   
---



### 텍스트 분석의 종류
1. 텍스트 분류
2. 감성 분석
3. 텍스트 요약
4. 텍스트 군집화와 유사도 측정

### 텍스트 분석 과정
1. 텍스트 사전 준비작업(=텍스트 전처리)
  * 클렌징, 대/소문자 변경, 특수문자 삭제 / 토큰화 작업 / 의미 없는 단어 제거 작업 / 어근 추출(Stemming, Lemmatization)

2. 피처 벡터화
  * BOW(Count 기반, TF-IDF 기반 벡터화), Word2Vec
3. ML 모델 수립 및 학습/예측/평가


### 파이썬 기반 NLP, 텍스트 분석 패키지
: NLTK, gensim, spaCy
  - NLTK는 굉장히 방대함. 다만 수행 속도가 아쉬운 측면이 있음. 실용적이지 않은 편
  - Gensim : 토픽 모델링 분야에서 자주 활용됨. Word2Vec 구현 가능
  - SpaCy : 수행 성능이 뛰어남


---



### 텍스트 분석 사전 준비 작업 = 텍스트 전처리 = 텍스트 정규화
1. 클렌징 : 불필요한 문자, 기호 제거
2. 토큰화 : 문장 토큰화 & 단어 토큰화 -- API 활용

    *BOW는 단어의 순서가 중요하지 않음.
    그래서 단어 토큰화만 사용하기도 함
    문장 토큰화는 각 문장의 semantic 의미가 중요할 때 사용*
    * 문장 토큰화 : 문장의 끝을 의미하는 기호를 찾아냄
      * ex) NLTK : sent_tokenize 활용
    * 단어 토큰화 : 공백, 콤마, 마침표, 정규 표현식 등을 이용해 단어를 분리
      * ex) word_tokenize()

    > 이렇게 문장을 단어 단위로 쪼갤 경우 문맥적인 의미가 무시되는 문제 발생
    ---> n-gram이 도입됨. 연속된 n개의 단어를 하나로 토큰화 함


---


3. 필터링 / Stop word 제거 / 철자 수정

    Stop word 제거 : 분석에 의미 없는 단어를 제거하는 과정. 언어별로 Stop word가 목록화 돼 있음 활용하면 된다.


4. Stemming & Lemmatization : 단어의 원형을 찾아가는 과정
  - Lemmatization이 더 정교한 결과를 제공함

    * NLTK : Porter, Lancaster, Snowball Stemmer // WordNetLemmatizer 제공



## BOW = Bag of Words
: 단어가 가지는 순서, 맥락을 무시하고 frequency 값을 부여해 피처 추출하는 모델

* 장점
  * 쉽고 빠른 구축
* 단점
  * 문맥 의미 (Semantic Context) 반영 부족. n_gram으로도 부족함
  * 희소 행렬 문제 : 한 문서에 수만~수십만개의 단어가 나타나는데, 문서마다 다른 단어가 나타남 --> 희소 행렬이 나타날 가능성이 매우 높음

### BOW 피처 벡터화

1. 정의 :
텍스트를 특정 의미를 가지는 벡터 값으로 변환하는 과정 = 피처 벡터화
BOW에서는 모든 문서에서 모든 단어를 칼럼으로 나열하고 각 문서에서 해당 단어의 횟수나 정규화된 빈도를 값으로 부여함

2. 종류 : count 기반의 벡터화 VS TF-IDF (Term Freq Inverse Document Freq)
  - TF-IDF는 모든 문서에서 전반적으로 많이 나타나는 단어에 페널티를 줌!!
  - 단순히 많이 나타난다고 점수를 잘 주는게 아니라, 이 문서에서 유난히 많이 나타나는 단어를 확인하고자 하는 것!!

3. 구현 방법 : CountVectorize, TfidfVectorize 클래스
  - CountVectorize 클래스 : 소문자 일괄 변환, 토큰화, 스톱 워드 필터링 + 피처벡터화 진행 & fit, transform 이용
    * 관련 파라미터
      * max_df : 너무 높은 빈도수인 단어 피처 제외하기 위한 freq high limit
        * 전체에서 공통적으로 나타나는 단어면 무의미할 확률 증가
      * min_df : 너무 낮은 빈도수인 단어 피처 제외하려는 freq low limit
      * max_features : 추출하는 피처의 개수를 제한
      * stop_words : 스톱 워드 파일 언어 지정


4. CountVectorize, TfidfVectorize 과정
  1) 영어면 소문자로 변경하는 과정 수행
  2) 디폴트 단어 기준으로 n_gram_range를 반영해 단어 토큰화 진행
  3) 텍스트 정규화 수행 : stop words, 어근 추출
  4) 피처 벡터화 진행


### BOW 희소행렬 변환
1. 희소행렬 - COO 형식
: 좌표 형식. 0이 아닌 데이터만 별도의 데이터 array에 저장하고 데이터가 가리키는 행과 열의 위치를 별도의 배열로 저장함

2. 희소행렬 - CSR 형식
: Compressed Sparse Row. 행이 바뀌는 지점만을 뽑아내서 저장하고 마지막에 데이터의 총 항목 개수를 추가.

In [3]:
from nltk import sent_tokenize
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. You feel it when you go to work, or go to church or pay your taxes.'

sentences = sent_tokenize(text=text_sample)

print(type(sentences),len(sentences))
print(sentences)

<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [5]:
from nltk import word_tokenize

sentence = "The Matrix is everywhere its all around us, here even in this room."
words = word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


In [6]:
from nltk import word_tokenize, sent_tokenize

def tokenize_text(text):
  sentences = sent_tokenize(text)
  word_tokens = [word_tokenize(sentence) for sentence in sentences]
  return word_tokens


word_tokens = tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
print('영어 stop words 갯수 : ', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 갯수 :  198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [9]:
import nltk
stopwords = nltk.corpus.stopwords.words('english')
all_tokens = []

for sentence in word_tokens:
  filtered_words =[]

  for word in sentence:
    word = word.lower() ## 소문자 변환

    if word not in stopwords:
      filtered_words.append(word)

  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


In [10]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


In [13]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma = WordNetLemmatizer()

print(lemma.lemmatize('working','v'), lemma.lemmatize('works','v'), lemma.lemmatize('worked','v'))
print(lemma.lemmatize('amusing','v'), lemma.lemmatize('amuses','v'), lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'), lemma.lemmatize('happiest','a'))
print(lemma.lemmatize('fancier','a'), lemma.lemmatize('fanciest','a'))

work work work
amuse amuse amuse
happy happy
fancy fancy


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [15]:
import numpy as np


dense = np.array([[3,0,1], [0,2,0]])

In [16]:
from scipy import sparse
data = np.array([3,1,2])

row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

In [17]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [18]:
[[0,0,1,0,0,5], [1,4,0,3,2,5], [0,6,0,3,0,0], [2,0,0,0,0,0], [0,0,0,7,0,8], [1,0,0,0,0,0]]

[[0, 0, 1, 0, 0, 5],
 [1, 4, 0, 3, 2, 5],
 [0, 6, 0, 3, 0, 0],
 [2, 0, 0, 0, 0, 0],
 [0, 0, 0, 7, 0, 8],
 [1, 0, 0, 0, 0, 0]]

In [19]:
from scipy import sparse
dense2 = np.array([[0,0,1,0,0,5],
                  [1,4,0,3,2,5],
                  [0,6,0,3,0,0],
                  [2,0,0,0,0,0],
                  [0,0,0,7,0,8],
                  [1,0,0,0,0,0]])


data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

row_pos = np.array([0,0,1,1,1,1,1,2,2,3,4,4,5])
col_pos = np.array([2,5,0,1,3,4,5,1,3,0,3,5,0])

sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

row_pos_ind = np.array([0,2,7,9,10,12,13])

sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print("COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인")
print(sparse_coo.toarray())
print("CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인")
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
